site_name: Edenmal Docs
repo_url: https://github.com/galexrt/docs.edenmal.moe
site_author: Alexander Trost
site_description: ""
use_directory_urls: true
theme:
  name: material
  font: false
  favicon: images/favicon.png
  logo: images/favicon.png
  palette:
    scheme: 'slate'
    primary: 'lime'
    accent: 'deep purple'
  icon:
    repo: fontawesome/brands/github
  features:
    - instant
    - navigation.expand
    - tabs
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      #js_files: []
  - redirects:
      redirect_maps: {}
markdown_extensions:
  - attr_list
  - meta
  - toc:
      permalink: true
  - tables
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  # Style is broken
  #- pymdownx.progressbar
  - pymdownx.snippets
  - pymdownx.superfences
  #- pymdownx.tabbed
