name: build-and-deploy
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: "squidfunk/mkdocs-material:latest"
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: false
      - name: Build
        run: |
          mkdocs build --clean
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
